# Generated by Django 5.0.1 on 2024-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
