# Generated by Django 5.0.1 on 2024-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='valid_till',
            field=models.DateTimeField(),
        ),
    ]
